In [ ]:
from bertopic import BERTopic
import pandas as pd

import re                                  
import string                             

from nltk.corpus import stopwords         
from nltk.stem import PorterStemmer        
from nltk.tokenize import TweetTokenizer   
from nltk.tokenize import word_tokenize

from nltk.stem import WordNetLemmatizer
from sklearn.feature_extraction.text import CountVectorizer

In [90]:
path1 = '/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 1.XLSX'

In [91]:
for i in range(1,12):
    print(f"df{i} = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence {i}.XLSX')")

df1 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 1.XLSX')
df2 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 2.XLSX')
df3 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 3.XLSX')
df4 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 4.XLSX')
df5 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 5.XLSX')
df6 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 6.XLSX')
df7 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 7.XLSX')
df8 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 8.XLSX')
df9 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 9.XLSX')
df10 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 10.XLSX')
df11 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 11.XLSX')

In [92]:
df1 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 1.XLSX')
df2 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 2.XLSX')
df3 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 3.XLSX')
df4 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 4.XLSX')
df5 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 5.XLSX')
df6 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 6.XLSX')
df7 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 7.XLSX')
df8 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 8.XLSX')
df9 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 9.XLSX')
df10 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 10.XLSX')
df11 = pd.read_excel('/Users/zamiulalam/Documents/Priyanka Sentiment Analysis/NY Times Data/Results list for_Artificial Intelligence 11.XLSX')

In [93]:
df = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8,df9,df10,df11], ignore_index=True)

In [94]:
df

,Title,Published date,Publication location,Publication,Publication type,Length,Section,Word count,Countries,Byline,...,Cite,Company,Headline,Hlead,Publication.1,Publication type.1,Pub-copyright,Show,Term,Ticker
0,OpenAI Unveils Web Browser Built for Artificia...,2025-10-21,New York,The New York Times,News,546,TECHNOLOGY,546,NaN,Cade Metz Cade Metz is a Times reporter who wr...,...,GOOGLE LLC,GOOGLE LLC,OpenAI Unveils Web Browser Built for Artificia...,OpenAI Unveils Web Browser Built for Artificia...,The New York Times,Web Publication,NaN,NaN,NaN,NaN
1,Meta Unveils Smart Glasses With Apps and an Ar...,2025-09-17,New York,The New York Times,News,453,TECHNOLOGY;personaltech,453,NaN,Eli Tan Eli Tan covers the technology industry...,...,NaN,NaN,Meta Unveils Smart Glasses With Apps and an Ar...,Meta Unveils Smart Glasses With Apps and an Ar...,The New York Times,Web Publication,NaN,NaN,NaN,NaN
2,"Margaret Boden, Philosopher of Artificial Inte...",2025-08-14,New York,The New York Times,News,1345,SCIENCE,1345,NaN,Michael S. Rosenwald,...,NaN,NaN,"Margaret Boden, Philosopher of Artificial Inte...","Margaret Boden, Philosopher of Artificial Inte...",The New York Times,Web Publication,NaN,NaN,NaN,NaN
3,Artificial Intelligence Will Destroy the Way W...,2025-11-03,New York,The New York Times,News,1068,Section A;Column 0;Editorial Desk;Pg. 18;GUEST...,1068,NaN,By Anastasia Berg,...,NaN,NaN,Artificial Intelligence Will Destroy the Way W...,Artificial Intelligence Will Destroy the Way W...,The New York Times,Newspaper,NaN,NaN,NaN,NaN
4,Bringing Art Back to Life With Artificial Inte...,2025-08-23,New York,The New York Times,News,1186,Section A;Column 0;Foreign Desk;Pg. 4,1186,NaN,By Ephrat Livni,...,BEAM GLOBAL,BEAM GLOBAL,Bringing Art Back to Life With Artificial Inte...,Bringing Art Back to Life With Artificial Inte...,The New York Times,Newspaper,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10262,An A.I. Soulmate And a Teen's Suicide,2024-11-02,New York,The New York Times,News,3197,Section B;Column 0;Business/Financial Desk;Pg....,3197,NaN,By Kevin Roose,...,NaN,NaN,An A.I. Soulmate And a Teen's Suicide,An A.I. Soulmate And a Teen's Suicide On the l...,The New York Times,Newspaper,NaN,NaN,NaN,NaN
10263,Can A.I. Be Blamed for a Teen’s Suicide? The S...,2024-10-23,New York,The New York Times,News,3225,TECHNOLOGY,3225,NaN,Kevin RooseKevin Roose is a Times technology c...,...,NaN,NaN,Can A.I. Be Blamed for a Teen’s Suicide? The S...,Can A.I. Be Blamed for a Teen’s Suicide? The S...,The New York Times,Web Publication,NaN,NaN,NaN,NaN
10264,The War in Ukraine May Be Impossible to Stop. ...,2022-05-31,New York,The New York Times,News,1509,OPINION,1509,NaN,Christopher Caldwell,...,SEA LTD,SEA LTD,The War in Ukraine May Be Impossible to Stop. ...,The War in Ukraine May Be Impossible to Stop. ...,The New York Times,Web Publication,NaN,NaN,NaN,NaN
10265,Microsoft dice que la nueva inteligencia artif...,2023-05-19,New York,The New York Times,News,1467,ESPANOL,1467,NaN,Cade Metz,...,MICROSOFT CORP,MICROSOFT CORP,Microsoft dice que la nueva inteligencia artif...,Microsoft dice que la nueva inteligencia artif...,The New York Times,Web Publication,NaN,NaN,NaN,NaN
10266,‘I Think We’re Heading Toward the Best World E...,2023-11-20,New York,The New York Times,News,4029,PODCASTS,4029,NaN,Kevin Roose,...,BEST INC,BEST INC,‘I Think We’re Heading Toward the Best World E...,‘I Think We’re Heading Toward the Best World E...,The New York Times,Web Publication,NaN,NaN,NaN,NaN

In [95]:
df.columns

Index(['Title', 'Published date', 'Publication location', 'Publication',
       'Publication type', 'Length', 'Section', 'Word count', 'Countries',
       'Byline', 'Agg-copyright', 'Cite', 'Company', 'Headline', 'Hlead',
       'Publication.1', 'Publication type.1', 'Pub-copyright', 'Show', 'Term',
       'Ticker'],
      dtype='object')

In [96]:
dff = df[['Hlead']]

In [97]:
dff

                                                   Hlead
0      OpenAI Unveils Web Browser Built for Artificia...
1      Meta Unveils Smart Glasses With Apps and an Ar...
2      Margaret Boden, Philosopher of Artificial Inte...
3      Artificial Intelligence Will Destroy the Way W...
4      Bringing Art Back to Life With Artificial Inte...
...                                                  ...
10262  An A.I. Soulmate And a Teen's Suicide On the l...
10263  Can A.I. Be Blamed for a Teen’s Suicide? The S...
10264  The War in Ukraine May Be Impossible to Stop. ...
10265  Microsoft dice que la nueva inteligencia artif...
10266  ‘I Think We’re Heading Toward the Best World E...

[10267 rows x 1 columns]

In [98]:
# create preprocess_text function
def preprocess_text(text):

    text = str(text)

    text = re.sub(r'—', '', text)

    # Remove months
    text = re.sub(r'\b(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\b', '', text)

    # Remove dates (1–31)
    text = re.sub(r'\b(?:[1-9]|[12][0-9]|3[01])\b', '', text)

    # Remove newspaper name in parentheses except (AI)
    text = re.sub(r'\s*\((?!AI\))[^)]*\)', '', text).strip()

    return text

# apply the function df

dff['Hleadz'] = dff['Hlead'].apply(preprocess_text)
dff

,Hlead,Hleadz
0,OpenAI Unveils Web Browser Built for Artificia...,OpenAI Unveils Web Browser Built for Artificia...
1,Meta Unveils Smart Glasses With Apps and an Ar...,Meta Unveils Smart Glasses With Apps and an Ar...
2,"Margaret Boden, Philosopher of Artificial Inte...","Margaret Boden, Philosopher of Artificial Inte..."
3,Artificial Intelligence Will Destroy the Way W...,Artificial Intelligence Will Destroy the Way W...
4,Bringing Art Back to Life With Artificial Inte...,Bringing Art Back to Life With Artificial Inte...
...,...,...
10262,An A.I. Soulmate And a Teen's Suicide On the l...,An A.I. Soulmate And a Teen's Suicide On the l...
10263,Can A.I. Be Blamed for a Teen’s Suicide? The S...,Can A.I. Be Blamed for a Teen’s Suicide? The S...
10264,The War in Ukraine May Be Impossible to Stop. ...,The War in Ukraine Be Impossible to Stop. And...
10265,Microsoft dice que la nueva inteligencia artif...,Microsoft dice que la nueva inteligencia artif...
10266,‘I Think We’re Heading Toward the Best World E...,‘I Think We’re Heading Toward the Best World E...

In [99]:
docs = dff['Hleadz'].tolist()

In [100]:
docs[0]

'OpenAI Unveils Web Browser Built for Artificial Intelligence The new browser, called Atlas, is designed to work closely with OpenAI products like ChatGPT. The new browser, called Atlas, is designed to work closely with OpenAI products like ChatGPT. OpenAI on Tuesday unveiled a free web browser that is designed to work closely with the company’s artificial intelligence technologies, including the chatbot ChatGPT.'

In [101]:
from sentence_transformers import SentenceTransformer
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

topic_model = BERTopic(
    embedding_model=embedding_model,
    vectorizer_model=CountVectorizer(stop_words="english"),
    min_topic_size=20
    )

topics, probs = topic_model.fit_transform(docs)

In [102]:
topic_model.get_topic_info()

,Topic,Count,Name,Representation,Representative_Docs
0,-1,3674,-1_new_intelligence_artificial_like,"[new, intelligence, artificial, like, mr, said...",[How to Cross the Government’s ‘Valley of Deat...
1,0,276,0_percent_500_stocks_wall,"[percent, 500, stocks, wall, nasdaq, composite...","[With Big Tech as an Anvil, Stocks Sink on Wal..."
2,1,217,1_energy_climate_gas_power,"[energy, climate, gas, power, electricity, coa...",[The Trump Bump On Your Energy Bills You do no...
3,2,166,2_israel_gaza_israeli_hamas,"[israel, gaza, israeli, hamas, iran, netanyahu...",[Israeli Troops in Gaza The war’s “next stage”...
4,3,155,3_students_school_schools_education,"[students, school, schools, education, college...","[A.I., Once the Future, Has Become The Present..."
...,...,...,...,...,...
106,105,21,105_hochul_state_kathy_budget,"[hochul, state, kathy, budget, gov, york, legi...",[N.Y. Lawmakers Target Prison Reform and A.I. ...
107,106,21,106_tax_agency_werfel_workers,"[tax, agency, werfel, workers, commissioners, ...",[I.R.S. Deploys Artificial Intelligence to Cat...
108,107,21,107_mccorduck_cognitive_schank_died,"[mccorduck, cognitive, schank, died, pamela, m...","[Roger C. Schank, Theorist of Artificial Intel..."
109,108,21,108_desert_birds_insects_trees,"[desert, birds, insects, trees, species, zebra...",[The Trouble with Trees To hear more audio sto...
110,109,20,109_apple_cook_tim_iphones,"[apple, cook, tim, iphones, tariffs, trump, pr...",[Trump Announces Additional $100 Billion Apple...

In [103]:
topic_model.get_representative_docs(95)

['The Banking Industry’s Go-to Crisis Adviser DealBook Newsletter Rodge Cohen is one of the most influential people behind the scenes of cleaning up the banking crisis. Rodge Cohen is one of the most influential people behind the scenes of cleaning up the banking crisis. Key adviser There are plenty of differences between the fallout from the collapse of Silicon Valley Bank and the 2008 financial crisis, but one similarity is the man trying to clean it up: H. Rodgin Cohen, known as Rodge, the senior chair at the law firm Sullivan & Cromwell. The soft-spoken Mr. Cohen was at the center of efforts to save Silicon Valley Bank and First Republic, the latter of which involved a call between the Federal Reserve chair Jerome Powell, Treasury Secretary Janet Yellen and the JPMorgan Chase boss Jamie Dimon. Here’s what to know about one of the most influential players in the banking crisis who isn’t making headlines. Mr. Cohen is a sought-after adviser in banking crises, and he has worked on almost every one in the last several decades. “Rodge is the banking lawyer’s go-to  there’s nobody who comes close to his level of reliability in the entire realm of substantive banking law,” said Sarah Raskin, a former deputy secretary of the Treasury. She added that she still finds herself in rooms of lawyers asking, “What would Rodge say?”',
 'Your Tuesday Briefing The sale of First Republic Bank. The sale of First Republic Bank. Officials move to contain U.S. banking crisis In the early hours of Monday morning, U.S. government officials seized First Republic Bank and then sold it to the country’s biggest bank, JPMorgan Chase. Their action appears, for now, to have quelled nearly two months of turmoil in the banking sector that followed the sudden collapse of Silicon Valley Bank and Signature Bank in early March. For Jamie Dimon, JPMorgan’s chief executive, it was a reprise of his role in the 2008 financial crisis, when JPMorgan acquired Bear Stearns and Washington Mutual at the behest of federal regulators. But the acquisition has also brought to the fore debates about whether some banks have become too big to fail partly because regulators have allowed or even encouraged them to acquire smaller financial institutions. JPMorgan is likely to make a lot of money from the acquisition, according to experts. JPMorgan will pay $. billion to acquire First Republic, and the government expects to cover a loss of about $ billion on First Republic’s assets. JPMorgan said that it expected the deal to raise its profit this year by $500 million.',
 "The Banking Industry's Go-To Adviser Is Trying to Clean Up a Crisis Rodge Cohen is one of the most influential people behind the scenes of cleaning up the banking crisis. Key adviser There are plenty of differences between the fallout from the collapse of Silicon Valley Bank and the 2008 financial crisis, but one similarity is the man trying to clean it up: H. Rodgin Cohen, known as Rodge, the senior chair at the law firm Sullivan & Cromwell . The soft-spoken Mr. Cohen was at the center of efforts to save Silicon Valley Bank and First Republic, the latter of which involved a call between the Federal Reserve chair Jerome Powell, Treasury Secretary Janet Yellen and the JPMorgan Chase boss Jamie Dimon. Here's what to know about one of the most influential players in the banking crisis who isn't making headlines. Mr. Cohen is a sought-after adviser in banking crises, and he has worked on almost every one in the last several decades. ''Rodge is the banking lawyer's go-to -- there's nobody who comes close to his level of reliability in the entire realm of substantive banking law,'' said Sarah Raskin, a former deputy secretary of the Treasury. She added that she still finds herself in rooms of lawyers asking, ''What would Rodge say?''"]

In [104]:
topic_model.visualize_topics()

In [105]:
topic_model.visualize_barchart()